"""First migration

Revision ID: 213693e216ef
Revises: 
Create Date: 2021-06-14 23:31:46.038131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213693e216ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
