"""Added breed column

Revision ID: 5ffe1c7c4bbf
Revises: fb6ccaad2afd
Create Date: 2021-06-14 22:30:55.659416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffe1c7c4bbf'
down_revision = 'fb6ccaad2afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
